fullnameOverride: webui
replicaCount: 1
image:
  repository: webui
  pullPolicy: Never
imagePullSecrets: []
service:
    type: ClusterIP
    internalPort: 10080
    externalPort: 10080
probes:
  enabled: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik-azds
  path: /
  tls: []
secrets: {}

secretsRef:
  - AppConfigurationConnectionString
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}