apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "mmm-iot-platform-ingress.ingressName" . }}
  annotations:
    kubernetes.io/ingress.class: {{ required "Error: missing required value .Values.subdomain" .Values.subdomain }}
    cert-manager.io/issuer: {{ include "mmm-iot-platform-ingress.issuerName" . }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - {{ include "mmm-iot-platform-ingress.fqdn" . }}
    secretName: {{ include "mmm-iot-platform-ingress.ingressName" . }}
  rules:
  - host: {{ include "mmm-iot-platform-ingress.fqdn" . }}
    http:
      paths:
      - backend:
          serviceName: reverse-proxy
          servicePort: 10080
        path: /(.*)