{{- $root := . -}}
{{- range $name, $values := .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{$name}}
type: opaque
data:
  {{- range $key,$value := $values }}
    {{- cat $key ": " ($value | b64enc) | nindent 2 }}
  {{- end }}
---
{{- end }}