trigger: none
pr: none
resources:
  pipelines:
    - pipeline: test
      source: azure-iot-platform-dotnet.ci.test
      trigger:
        branches:
          - master
pool:
  vmImage: ubuntu-latest
variables:
  ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
    _imageTag: $(resources.pipeline.test.runID)
  ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
    _imageTag: $(imageTag)
stages:
  - stage: checkParameters
    displayName: Check parameters
    dependsOn: []
    jobs:
      - job: checkParameters
        displayName: Check parameters
        steps:
          - checkout: none

          - script: |-
              set -Eeuxo pipefail
              echo "Image tag: '$(_imageTag)'"
              if [ -z "$(_imageTag)" ]
              then
                echo "A value for the 'imageTag' variable must be provided" > /dev/stderr
                exit 1
              fi
            displayName: Check parameters

  - stage: printPipelineResourceVariables
    displayName: Print pipeline resource variables
    dependsOn: []
    jobs:
      - job: printPipelineResourceVariables
        displayName: Print pipeline resource variables
        steps:
          - checkout: none

          - template: ../templates/print-pipeline-resource-variables.yaml
            parameters:
              pipelineResourceName: test

  - stage: crslDev
    displayName: CRSL dev
    dependsOn:
      - checkParameters
    condition: and(succeeded(), eq(variables['runCrslDevStage'], 'true'))
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_CRSL_Environment_Dev
          subscriptionName: 3M-CRSLAD16-BBIoTP-DEV
          applicationCode: crsliot
          applicationShortCode: crsl
          environmentCategory: dev
          imageTag: $(_imageTag)
          subscriptionId: c36fb2f8-f98d-40d0-90a9-d65e93acb428

  - stage: ggkDev
    displayName: GGK dev
    dependsOn:
      - checkParameters
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: GGK-Environment
          subscriptionName: 3M-CRSLAD16-BBIoTP-DEV
          applicationCode: ggktech
          applicationShortCode: ggk
          environmentCategory: dev
          imageTag: $(_imageTag)
          subscriptionId: c36fb2f8-f98d-40d0-90a9-d65e93acb428

  - stage: crslQa
    displayName: CRSL QA
    dependsOn:
      - crslDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_CRSL_Environment_QA
          subscriptionName: 3M-CRSLAD17-BBIoTP-QA
          applicationCode: crsliot
          applicationShortCode: crsl
          environmentCategory: qa
          imageTag: $(_imageTag)
          subscriptionId: f27c7c03-1ea8-49b8-9878-106e434b8a23

  - stage: crslWkbnch
    displayName: CRSL workbench
    dependsOn:
      - crslQa
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_CRSL_Environment_Wkbnch
          subscriptionName: 3M-CRSLAD19-BBIoTP-Prod
          applicationCode: crsliot
          applicationShortCode: crsl
          environmentCategory: wkbnch
          imageTag: $(_imageTag)
          subscriptionId: dcb37438-95ca-4a68-812d-39ce0d591df2

  - stage: chimDev
    displayName: CHIM dev
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_CHIM_Environment_DEV
          subscriptionName: 3M-ACTAIR01-CHIMSMART-Dev
          applicationCode: chimiot
          applicationShortCode: chim
          environmentCategory: dev
          imageTag: $(_imageTag)
          subscriptionId: 28299656-8110-4dc4-a33f-82a6cc3d05c2

  - stage: chimQa
    displayName: CHIM QA
    dependsOn:
      - chimDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_CHIM_Environment_QA
          subscriptionName: 3M-ACTAIR02-CHIMSMART-QA
          applicationCode: chimiot
          applicationShortCode: chim
          environmentCategory: qa
          imageTag: $(_imageTag)
          subscriptionId: 30975220-85e1-4769-8bc1-4542ec8569a0

  - stage: chimProd
    displayName: CHIM prod
    dependsOn:
      - chimQa
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_CHIM_Environment_PROD
          subscriptionName: 3M-ACTAIR04-CHIMSMART-Prod
          applicationCode: chimiot
          applicationShortCode: chim
          environmentCategory: prod
          imageTag: $(_imageTag)
          subscriptionId: 5401dcf9-9d00-445b-97b4-60b216ea4930

  - stage: psdDev
    displayName: PSD dev
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_DEV
          subscriptionName: 3M-ASDT04-PSD-CS-IOT-Dev
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory: dev
          imageTag: $(_imageTag)
          subscriptionId: 1d0a4e20-e44d-43b5-97b0-9b577f5bf048

  - stage: psdQa
    displayName: PSD QA
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_QA
          subscriptionName: 3M-ASDT05-PSD-CS-IOT-QA
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory:  qa
          imageTag: $(_imageTag)
          subscriptionId: 8c550fc0-24e0-43cb-8237-5fbb168c1071

  - stage: psdEu
    displayName: PSD EU
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_EU
          subscriptionName: 3M-ASDT07-PSD-CS-IOT-Prod
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory: eu
          imageTag: $(_imageTag)
          subscriptionId: 71fd3c60-f2c3-4e78-ad18-7e370fe3b068

  - stage: psdStg
    displayName: PSD staging
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_STG
          subscriptionName: 3M-ASDT05-PSD-CS-IOT-QA
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory: stg
          imageTag: $(_imageTag)
          subscriptionId: 8c550fc0-24e0-43cb-8237-5fbb168c1071

  - stage: psdProd
    displayName: PSD Prod
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_Prod
          subscriptionName: 3M-ASDT07-PSD-CS-IOT-Prod
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory: prod
          imageTag: $(_imageTag)
          subscriptionId: 71fd3c60-f2c3-4e78-ad18-7e370fe3b068

  - stage: emdDev
    displayName: EMD dev
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_EMD_Environment_DEV
          subscriptionName: 3M-UDAH02-SpartanIotHub-Dev
          applicationCode: emdiot
          applicationShortCode: emd
          environmentCategory: dev
          imageTag: $(_imageTag)
          subscriptionId: 191495e8-b878-4140-85eb-aae73a7119cd

  - stage: emdQa
    displayName: EMD QA
    dependsOn:
      - emdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_EMD_Environment_QA
          subscriptionName: 3M-UDAH03-SpartanIotHub-QA
          applicationCode: emdiot
          applicationShortCode: emd
          environmentCategory: qa
          imageTag: $(_imageTag)
          subscriptionId: 5248a0ea-c79b-4739-adc7-e76eeb27e253

  - stage: emdCt
    displayName: EMD CT
    dependsOn:
      - emdQa
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_EMD_Environment_CT
          subscriptionName: 3M-UDAH04-SpartanIotHub-CT
          applicationCode: emdiot
          applicationShortCode: emd
          environmentCategory: ct
          imageTag: $(_imageTag)
          subscriptionId: e9f61243-5e9a-4b8a-918c-09fe7e9f1ec1