trigger: none
pr: none
pool:
  vmImage: ubuntu-latest
variables:
  locationName: eastus2
stages:
  - stage: chimDev
    displayName: CHIM dev
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: 3M-ACTAIR01-CHIMSMART-Dev
          locationName: $(locationName)
          appInsightsLocation: eastus
          environmentName: IoT_CHIM_Environment_DEV
          subscriptionId: 28299656-8110-4dc4-a33f-82a6cc3d05c2
          applicationCode: chimiot
          applicationShortCode: chim
          environmentCategory: dev
          kubernetesVersion: 1.16.10
          sendgridEmail: blinzie@mmm.com
          sysAdmins: '[{"UserId": "3e30f301-4f57-4b3e-949a-3ff8e93870b5", "Name": "Viswanath Kotha CW"}, {"UserId": "00e4068a-944e-4cd2-bc2a-77b1d33a1db3", "Name": "Jonathan Asbury"}, {"UserId": "295af21b-90af-4777-b0ba-4d7f94514679", "Name": "Sean Dubiel"}, {"UserId": "534a9d20-04aa-4f42-9cf9-d82fca6cf7df", "Name": "Ragavender Basangari CW"}, {"UserId": "a2dc5d37-94cc-4fd6-91bb-8a26458d8089", "Name": "Anant Choudhari CW"}, {"UserId": "866aa8d9-a571-4b3e-8acd-de710e74342d", "Name": "Nick Gawryk"}, {"UserId": "9f8df5ac-6312-4245-be6d-ff6bb70ac1e1", "Name": "Jayasimha Nallagatla CW"}, {"UserId": "b3bbea27-2e63-4f95-8197-e9869af64b14", "Name": "Sahithi Voruganti CW"}, {"UserId": "ec9745fa-9fa9-4d35-ab55-1e3bd064c4a2", "Name": "Andrew Schmidt"}, {"UserId": "f6a7ba19-0f66-4cc6-9d15-2241f40fc122", "Name": "Joseph Bethke"}, {"UserId": "c8efa307-f285-4fb2-91ae-5d4061d2b271", "Name": "Jonathan Asbury CW"}, {"UserId": "a0ee6a74-65e7-4885-9219-d92982a7e04a", "Name": "Kyle Estes CW"}, {"UserId": "4a0b6ddb-38ef-46dd-928b-e7ffed63963c", "Name": "Rakesh Satelli CW"}, {"UserId": "f8b35420-6ee3-4d4d-a757-e7ffe4f4f791", "Name": "Brad Murray"}, {"UserId": "8688e410-cc82-4d84-84c3-a8e013c7785f", "Name": "Brian Linzie"}, {"UserId": "18a00c2a-2a99-4815-9c97-412300004fcf", "Name": "Anup Warade CW"}]'

  - stage: chimQa
    displayName: CHIM QA
    dependsOn:
      - chimDev
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: 3M-ACTAIR02-CHIMSMART-QA
          locationName: $(locationName)
          appInsightsLocation: eastus
          environmentName: IoT_CHIM_Environment_QA
          subscriptionId: 30975220-85e1-4769-8bc1-4542ec8569a0
          applicationCode: chimiot
          applicationShortCode: chim
          environmentCategory: qa
          kubernetesVersion: 1.16.10
          sendgridEmail: blinzie@mmm.com
          sysAdmins: '[{"UserId": "3e30f301-4f57-4b3e-949a-3ff8e93870b5", "Name": "Viswanath Kotha CW"}, {"UserId": "00e4068a-944e-4cd2-bc2a-77b1d33a1db3", "Name": "Jonathan Asbury"}, {"UserId": "295af21b-90af-4777-b0ba-4d7f94514679", "Name": "Sean Dubiel"}, {"UserId": "534a9d20-04aa-4f42-9cf9-d82fca6cf7df", "Name": "Ragavender Basangari CW"}, {"UserId": "a2dc5d37-94cc-4fd6-91bb-8a26458d8089", "Name": "Anant Choudhari CW"}, {"UserId": "866aa8d9-a571-4b3e-8acd-de710e74342d", "Name": "Nick Gawryk"}, {"UserId": "9f8df5ac-6312-4245-be6d-ff6bb70ac1e1", "Name": "Jayasimha Nallagatla CW"}, {"UserId": "b3bbea27-2e63-4f95-8197-e9869af64b14", "Name": "Sahithi Voruganti CW"}, {"UserId": "ec9745fa-9fa9-4d35-ab55-1e3bd064c4a2", "Name": "Andrew Schmidt"}, {"UserId": "f6a7ba19-0f66-4cc6-9d15-2241f40fc122", "Name": "Joseph Bethke"}, {"UserId": "c8efa307-f285-4fb2-91ae-5d4061d2b271", "Name": "Jonathan Asbury CW"}, {"UserId": "a0ee6a74-65e7-4885-9219-d92982a7e04a", "Name": "Kyle Estes CW"}, {"UserId": "4a0b6ddb-38ef-46dd-928b-e7ffed63963c", "Name": "Rakesh Satelli CW"}, {"UserId": "f8b35420-6ee3-4d4d-a757-e7ffe4f4f791", "Name": "Brad Murray"}, {"UserId": "8688e410-cc82-4d84-84c3-a8e013c7785f", "Name": "Brian Linzie"}, {"UserId": "18a00c2a-2a99-4815-9c97-412300004fcf", "Name": "Anup Warade CW"}]'

  - stage: chimProd
    displayName: CHIM prod
    dependsOn:
      - chimQa
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: 3M-ACTAIR04-CHIMSMART-PROD
          locationName: $(locationName)
          appInsightsLocation: eastus
          environmentName: IoT_CHIM_Environment_Prod
          subscriptionId: 5401dcf9-9d00-445b-97b4-60b216ea4930
          applicationCode: chimiot
          applicationShortCode: chim
          environmentCategory: prod
          kubernetesVersion: 1.16.10
          sendgridEmail: blinzie@mmm.com
          sysAdmins: '[{"UserId": "ec9745fa-9fa9-4d35-ab55-1e3bd064c4a2", "Name": "Andrew Schmidt"}, {"UserId": "295af21b-90af-4777-b0ba-4d7f94514679", "Name": "Sean Dubiel"}, {"UserId": "866aa8d9-a571-4b3e-8acd-de710e74342d", "Name": "Nick Gawryk"}, {"UserId": "f6a7ba19-0f66-4cc6-9d15-2241f40fc122", "Name": "Joseph Bethke"}, {"UserId": "a0ee6a74-65e7-4885-9219-d92982a7e04a", "Name": "Kyle Estes CW"}, {"UserId": "f8b35420-6ee3-4d4d-a757-e7ffe4f4f791", "Name": "Brad Murray"}, {"UserId": "8688e410-cc82-4d84-84c3-a8e013c7785f", "Name": "Brian Linzie"}]'